# permissions for end users to edit virtualrouters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualrouter-editor-role
rules:
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualrouters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualrouters/status
  verbs:
  - get
