# permissions for end users to view virtualnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualnode-viewer-role
rules:
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualnodes/status
  verbs:
  - get
