# permissions for end users to view virtualservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualservice-viewer-role
rules:
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualservices/status
  verbs:
  - get
