# permissions for end users to view virtualrouters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualrouter-viewer-role
rules:
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualrouters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualrouters/status
  verbs:
  - get
