name: integration-test
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run integration test action
        uses: ./.github/actions/integration-test
        with:
          aws_role: "${{ secrets.CI_AWS_ROLE }}"
          vpc_id: "${{ secrets.INTEG_TEST_VPC }}"
          account_id: "${{ secrets.CI_AWS_ACCOUNT }}"
