name: prod-release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag for this release (must already be pushed).'
        required: true

permissions:
  contents: read

jobs:
  prod-release:
    name: prod-release
    runs-on: ubuntu-18.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials (beta)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.BETA_AWS_ROLE }}
          role-session-name: ControllerProdRelease
      - name: Pull docker images
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${{ secrets.BETA_AWS_ACCOUNT }}.dkr.ecr.us-west-2.amazonaws.com
          docker pull ${{ secrets.BETA_AWS_ACCOUNT }}.dkr.ecr.us-west-2.amazonaws.com/amazon/appmesh-controller:${{ github.event.inputs.tag }}-linux_arm64
          docker pull ${{ secrets.BETA_AWS_ACCOUNT }}.dkr.ecr.us-west-2.amazonaws.com/amazon/appmesh-controller:${{ github.event.inputs.tag }}-linux_amd64

      - name: Configure AWS Credentials (prod)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.PROD_AWS_ROLE }}
          role-session-name: ControllerProdRelease
      - name: Push Images To ECR Public
        shell: bash
        env:
          SRC_IMAGE: "${{ secrets.BETA_AWS_ACCOUNT }}.dkr.ecr.us-west-2.amazonaws.com/amazon/appmesh-controller"
          DST_IMAGE: "public.ecr.aws/amazon/appmesh-controller"
          TAG: "${{ github.event.inputs.tag }}"
          AMD_TAG: "${{ github.event.inputs.tag }}-linux_amd64"
          ARM_TAG: "${{ github.event.inputs.tag }}-linux_arm64"
        run: |
          aws ecr-public get-login-password --region "${{ inputs.region }}" | \
            docker login --username AWS --password-stdin "public.ecr.aws"
          docker tag "$SRC_IMAGE:$AMD_TAG" "$DST_IMAGE:$AMD_TAG"
          docker tag "$SRC_IMAGE:$ARM_TAG" "$DST_IMAGE:$ARM_TAG"
          docker push "$DST_IMAGE:$AMD_TAG"
          docker push "$DST_IMAGE:$ARM_TAG"
          docker manifest create "$DST_IMAGE:$TAG" "$DST_IMAGE:$AMD_TAG" "$DST_IMAGE:ARM_TAG"
          docker manifest push "$DST_IMAGE:$TAG"

      - name: Deploy Images to US
          uses: ./.github/actions/push-image
          with:
            source_image: "${{ secrets.BETA_AWS_ACCOUNT }}.dkr.ecr.us-west-2.amazonaws.com/amazon/appmesh-controller"
            image_tag: "${{ github.event.inputs.tag }}"
            region: "us-west-2"
            repo_host: "${{ secrets.PROD_AWS_ACCOUNT }}.dkr.ecr.us-west-2.amazonaws.com"
            role: "${{ secrets.PROD_AWS_ROLE }}"

